# Generated by Django 4.0.4 on 2022-05-22 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodels',
            name='desc',
        ),
    ]
